### ISSUE TITLE
Add Sign up User in Existing Created Group

### ISSUE THREAD

**Issue by nirav700** [mitchellporter/Halfsies#15]
My Friends Create new group say for example 'Friends Group' and send me invitation mail, and then i have sign up with application,thats working fine but is it possible i am directly add in newly created Friends group or should i first fetch all group details from quick blox and add my id to specific group.

**Comment by mitchellporter** [comment]
This project isn't actively maintained anymore and hasn't been for awhile now, but if you'd like to make any updates and submit a pull request go for it.

Cheers.
