### ISSUE TITLE
Adding friends not working

### ISSUE THREAD

**Issue by wellkunnected** [mitchellporter/Halfsies#16]
I ran this app on my iPhone and my friends iPhone and although we both showed up within the app, adding each other never worked. I was trying to see the end result of how the photo would look after us both taking a picture but for some reason each time I click my friends name to send him a photo the dialogue shows "you need some friends!" And takes me through adding him again. Not sure if anyone else has had this issue or what it could be on my end. I have my Parse app setup to hold the user data but for some reason it won't let me add anyone using the app.

**Comment by mitchellporter** [comment]
Have you setup a cloud code file? That's what powers the friend adding functionality.

**Comment by wellkunnected** [comment]
No I haven't, please excuse me but I am a beginner and wouldn't know where
to start to do that. How would I setup a "cloud code file"?

On Tue, Feb 9, 2016 at 1:25 PM, Mitchell Porter <notifications@github.com>
wrote:

> Have you setup a cloud code file? That's what powers the friend adding
> functionality.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellporter/Halfsies/issues/16#issuecomment-181991806>
> .
>



-- 




Founded Well Kunnected, Inc 2010

**Comment by mitchellporter** [comment]
No worries :)

You can learn about creating a cloud code file on Parse.com

Then take a look at my other repo: https://github.com/mitchellporter/friends-relation-parse-cloud-code

**Comment by wellkunnected** [comment]
Awesome! I read about the cloud code file on Parse and I have no clue as to
where to get started :D The link to your other repo, what am I doing with
that file? And how would I integrate that with the current Halfsies project?

On Tue, Feb 9, 2016 at 3:25 PM, Mitchell Porter <notifications@github.com>
wrote:

> No worries :)
>
> You can learn about creating a cloud code file on Parse.com
>
> Then take a look at my other repo:
> https://github.com/mitchellporter/friends-relation-parse-cloud-code
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mitchellporter/Halfsies/issues/16#issuecomment-182046412>
> .
>



-- 




Founded Well Kunnected, Inc 2010

**Comment by mitchellporter** [comment]
Parse.com has all the documentation you could ever need on creating a new cloud code files, triggering it's functions from the iOS SDK, etc.
